### ISSUE TITLE
Question about parameter initialProgram to spa.

### ISSUE THREAD

**Issue by rluiten** [andrejewski/raj-spa#34]
Just a some thoughts around raj-spa.
I am exploring this hope you don't mind some possibly dumb questoins.

I am just implementing raj-spa in typescript.
I have simplified it a bit at moment to not have promised programs or keyed programs, I plan to add those later. I just have the types nailed down to something that works but I am not totally happy with ye as each program managed by the spa could have its own unique state type and message type so I am considering how to approach this or maybe I can leave them as `any` types as the spa itself doesn't really care.

I also used a simple hash router as you describe in the doc of raj-spa. I think giving an example router is a very good idea in your doc. You might consider including one in raj-spa source.

I got simple example spa running and looking at behaviour and noticed I never saw `initialProgram`.
What I see is that the subscribe() to router in `raj-spa.init()` triggers dispatch of the hash route which causes the GetRoute and sets the program based upon route before I ever seen `initialProgram` parameter to raj-spa. I realise if the router was async that `initialProgram` could be displayed before program is updated by router, but this got me thinking about maybe init should lean on `getRouteProgram` to set initial program ?

**Comment by andrejewski** [comment]
> I just have the types nailed down to something that works but I am not totally happy with it as each program managed by the spa could have its own unique state type and message type so I am considering how to approach this

I am super interested to see if there's a good way to type this. I've personally given it some thought and it eventually as you say breaks down to anys. If we could solve this problem generically a lot would fall into place for typing other HOPs, it might even be something to give back to Elm.

> You might consider including one in raj-spa source.

I don't provide a router in library because there's so much to support. I've used hash-change, push-state, and even simple string dispatch in the case of React Native. When it comes to browser history everyone always wants their own special thing. We could have router implementations as libraries though it's not too much work to take an existing router tool and wrap it in the router interface.

> maybe init should lean on getRouteProgram to set initial program?

For context, originally all effects were called in a `setTimeout(() => { ... }, 0)` in Raj. I removed that before 1.0 because it wasn't necessary. So when `raj-spa` was written it had that constraint and the initialProgram would have a chance to render once before the router responded with its first dispatch. 

The `initialProgram` is really like an initial loading screen the way I intended it to be used. Making it a program as opposed to a view function was to allow fancy animation or data loading for that view. Not seeing the initialProgram at all is ideal. Between having promised programs and not always being able to guarantee that the router can emit the first route synchronously (it's preferred but not required as it is potentially impossible in some contexts without doing something async), I think the way it is written now is fine. In your trimmed down version, it may make more sense.

---

I have been thinking about how to decouple the promise resolution bit of `raj-spa` to be its own library. If you have thoughts on that I'd be interested to hear them. The big thing about having promises in spa is to have the `isTransitioning` flag to show a loading indicator on the previous page while the next page loads. So maybe it can't be removed but we can have a subset of functionality in a new package. I have not found a good use case for that though, async loading is always coupled to routing for me.

**Comment by rluiten** [comment]
I don't expect to resolve the types much better than `any` really if it was a tractable problem Id expect to have seen it around, I will think about it some more.

Your explanations fit with what I saw, I actually added setTimeout to the dispatch from the router to see the `initialProgram` render at one point.

One reason I was happy to see the example router in your doc is it means someone can get something running real fast. I would have thought there'd be two main web router variants hash and push state, most anything else on web would be variant I would have thought and having those as a starting state is useful for most people IMO.

I did manage to figure out `isTransitioning` correctly looks like.

Thanks for the detailed response.

**Comment by andrejewski** [comment]
> One reason I was happy to see the example router in your doc is it means someone can get something running real fast.

I've made a to-do to write up a markdown page with some different routers that will live in the `raj-spa` project. I don't want to support any more than these copy/paste examples because I don't have the bandwidth.

Thanks for looking into this and other Raj projects so closely, I appreciate it.
